/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* ── Airtable Design System Tokens (DESIGN-airtable.md) ── */
        primary: {
          DEFAULT: '#181d26', // Near-black ink: dominant brand color
          active: '#0d1218',
          hover: '#0d1218',
          dark: '#0d1218',
          soft: '#f8fafc',
        },
        ink: {
          DEFAULT: '#181d26',
          body: '#333840',
          muted: '#41454d',
          light: '#9297a0',
        },
        body: '#333840',
        muted: '#41454d',
        hairline: '#dddddd',
        'border-strong': '#9297a0',
        canvas: '#ffffff',
        'surface-soft': '#f8fafc',
        'surface-strong': '#e0e2e6',
        'surface-dark': '#181d26',
        'surface-dark-elevated': '#1d1f25',

        /* ── Signature Brand Voltage Cards (Full-bleed surfaces) ── */
        signature: {
          coral: '#aa2d00',
          forest: '#0a2e0e',
          cream: '#f5e9d4',
          peach: '#fcab79',
          mint: '#a8d8c4',
          yellow: '#f4d35e',
          mustard: '#d9a441',
        },

        /* ── Semantic & Interactive ── */
        link: {
          DEFAULT: '#1b61c9',
          active: '#1a3866',
        },
        info: {
          DEFAULT: '#254fad',
          border: '#458fff',
        },
        success: {
          DEFAULT: '#006400',
          border: '#39bf45',
        },
        'pricing-ink': '#1d1f25',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',

        /* ── Compatibility Aliases for Existing App Code ── */
        'canvas-light': '#ffffff',
        'canvas-card': '#ffffff',
        'canvas-cream': '#f5e9d4',
        'canvas-night': '#181d26',
        'canvas-night-elevated': '#1d1f25',
        'surface-elevated-dark': '#1d1f25',
        'hairline-light': '#dddddd',
        'hairline-dark': '#333840',
        'shade-30': '#e0e2e6',
        'shade-40': '#cbd5e1',
        'shade-50': '#9297a0',
        'shade-60': '#41454d',
        'shade-70': '#333840',
        aloe: '#0a2e0e',
        'aloe-10': '#a8d8c4',
        pistachio: '#a8d8c4',

        humanitarian: {
          blue: '#1b61c9',
          'blue-soft': '#eff6ff',
          sage: '#0a2e0e',
          'sage-soft': '#f0fdf4',
          amber: '#d9a441',
          'amber-soft': '#fefce8',
          rose: '#aa2d00',
          'rose-soft': '#fff1f2',
          teal: '#0d9488',
          'teal-soft': '#f0fdfa',
          indigo: '#254fad',
          'indigo-soft': '#eef2ff',
          slate: '#41454d',
          'slate-soft': '#f8fafc',
        },
        brand: {
          DEFAULT: '#ea580c',
          hover: '#c2410c',
          active: '#9a3412',
          soft: '#fff7ed',
          border: '#fed7aa',
        },
      },
      fontFamily: {
        brand: [
          'Outfit',
          'Inter Variable',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        display: [
          'Inter Variable',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        body: [
          'Inter Variable',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      borderRadius: {
        xs: '2px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        pill: '9999px',
        full: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
        'sm-space': '8px',
        'md-space': '12px',
        'lg-space': '16px',
        'xl-space': '24px',
        'huge': '64px',
      },
      boxShadow: {
        'elevation-1': '0 1px 2px rgba(15, 23, 42, 0.05)',
        'elevation-2': '0 0 0 1px #e2e8f0, 0 2px 4px rgba(15, 23, 42, 0.05)',
        'elevation-3': '0 0 0 1px #e2e8f0, 0 8px 16px rgba(15, 23, 42, 0.08)',
        'elevation-4': '0 0 0 1px #e2e8f0, 0 16px 32px rgba(15, 23, 42, 0.12)',
        'card': '0 1px 3px 0 rgb(15 23 42 / 0.04), 0 1px 2px -1px rgb(15 23 42 / 0.04)',
        'card-hover': '0 4px 6px -1px rgb(15 23 42 / 0.07), 0 2px 4px -2px rgb(15 23 42 / 0.07)',
        'dropdown': '0 10px 15px -3px rgb(15 23 42 / 0.08), 0 4px 6px -4px rgb(15 23 42 / 0.04)',
        'button-focus': '0 0 0 2px #ffffff, 0 0 0 4px #ea580c',
      },
    },
  },
  plugins: [],
}
