/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#1e40af',
          hover: '#1d4ed8',
          dark: '#1e3a8a',
          soft: '#eff6ff',
        },
        ink: {
          DEFAULT: '#0f172a',
          muted: '#475569',
          light: '#94a3b8',
        },
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        'canvas-light': '#f8fafc',
        'canvas-card': '#ffffff',
        'canvas-cream': '#f1f5f9',
        'canvas-night': '#0f172a',
        'canvas-night-elevated': '#1e293b',
        'surface-elevated-dark': '#1e293b',
        
        /* Humanitarian Semantic Status Colors */
        humanitarian: {
          blue: '#1e40af',
          'blue-soft': '#eff6ff',
          sage: '#059669',
          'sage-soft': '#ecfdf5',
          amber: '#d97706',
          'amber-soft': '#fffbeb',
          rose: '#dc2626',
          'rose-soft': '#fef2f2',
          teal: '#0d9488',
          'teal-soft': '#f0fdfa',
          indigo: '#4f46e5',
          'indigo-soft': '#eef2ff',
          slate: '#475569',
          'slate-soft': '#f1f5f9',
        },

        /* Backward compatibility aliases */
        aloe: '#10b981',
        'aloe-10': '#ecfdf5',
        pistachio: '#d1fae5',
        'pistachio-10': '#d1fae5',
        'shade-30': '#e2e8f0',
        'shade-40': '#cbd5e1',
        'shade-50': '#64748b',
        'shade-60': '#475569',
        'shade-70': '#334155',
        'hairline-light': '#e2e8f0',
        'hairline-dark': '#334155',
      },
      fontFamily: {
        display: [
          'Inter Variable',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Noto Sans Devanagari',
          'Noto Sans Bengali',
          'Noto Sans Tamil',
          'Noto Sans Telugu',
          'Noto Sans Gujarati',
          'Noto Sans Gurmukhi',
          'Noto Sans Kannada',
          'Noto Sans Malayalam',
          'Noto Sans Oriya',
          'Noto Nastaliq Urdu',
          'sans-serif',
        ],
        body: [
          'Inter Variable',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Noto Sans Devanagari',
          'Noto Sans Bengali',
          'Noto Sans Tamil',
          'Noto Sans Telugu',
          'Noto Sans Gujarati',
          'Noto Sans Gurmukhi',
          'Noto Sans Kannada',
          'Noto Sans Malayalam',
          'Noto Sans Oriya',
          'Noto Nastaliq Urdu',
          'sans-serif',
        ],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        pill: '9999px',
      },
      spacing: {
        'xxs': '2px',
        'xs': '4px',
        'sm-space': '8px',
        'md-space': '12px',
        'lg-space': '16px',
        'xl-space': '24px',
        'xxl': '32px',
        'huge': '64px',
      },
      boxShadow: {
        'elevation-1': '0 1px 3px rgba(15, 23, 42, 0.08), 0 1px 2px rgba(15, 23, 42, 0.04)',
        'elevation-2': '0 4px 6px -1px rgba(15, 23, 42, 0.08), 0 2px 4px -1px rgba(15, 23, 42, 0.04)',
        'elevation-3': '0 10px 15px -3px rgba(15, 23, 42, 0.07), 0 4px 6px -2px rgba(15, 23, 42, 0.03), 0 0 0 1px rgba(15, 23, 42, 0.05)',
        'elevation-4': '0 20px 25px -5px rgba(15, 23, 42, 0.1), 0 10px 10px -5px rgba(15, 23, 42, 0.04)',
      },
    },
  },
  plugins: [],
}
